### ISSUE TITLE
'builtin_function_or_method' object has no attribute 'train'

### ISSUE THREAD

**Issue by museverse9** [rionaldichandraseta/facifier#1]
In train_gender_classifier:
 if (fisher_face.predict(image)[0] == prediction_labels[idx]):

TypeError: 'int' object is not subscriptable

**Comment by chandraseta** [comment]
Could you specify what version of Python you're using? Because I could not reproduce such errors in my environment. Thanks

**Comment by museverse9** [comment]
python 3.6. removing [0] from that line helped
