### ISSUE TITLE
the models havent been trained

### ISSUE THREAD

**Issue by museverse9** [rionaldichandraseta/facifier#2]
the models havent been trained . u have included empty models with just file names

**Comment by chandraseta** [comment]
The model has indeed been trained, however I just found out that a model trained in Linux could not run in Windows and vice versa. I'm working on training separate model for different OS

**Comment by chandraseta** [comment]
I've added Windows-friendly models, please follow the instructions in the README to use them. Thanks.

**Comment by museverse9** [comment]
Can you tell how to train models using imdb wiki dataset

**Comment by chandraseta** [comment]
The IMDB-Wiki dataset is, sadly, not yet labelled/classified. That means you have to label or separate each of the pictures individually.

I will add the instructions in README shortly.

**Comment by museverse9** [comment]
Okay. So when you say you've trained using imdb, kdef, normal, it is using
labels male, female and taking photos from those datasets?

**Comment by chandraseta** [comment]
The labels are created automatically by `gender_data_prep.py` and `emotion_data_prep.py`.

This is the folder structure
```
├── data
    ├── raw_emotion
    ├── raw_gender
        ├── female
        ├── male
└── src
```

Put the images with female faces in `data/raw_gender/female`, and it will be automatically labelled as "female". Meanwhile, put the images with male faces in 'data/raw_gender/male' to label it as "male"

**Comment by museverse9** [comment]
Ya. Thank you.
