### ISSUE TITLE
find_faces can't find face in small size pictures. (5kb)

### ISSUE THREAD

**Issue by sionking** [rionaldichandraseta/facifier#3]
I am trying some Instagram profile pictures to detect mostly gender, but the find_faces method return empty.
Any suggestions?

**Comment by chandraseta** [comment]
Can you link the picture?

The find_faces method uses HaarCascade classifier provided by OpenCV and is not very powerful. It sometimes fails to detect the face of people wearing glasses, especially sunglasses. Moreover, it may fail to detect angled faces, i.e. faces not looking roughly in the direction of the camera..

**Comment by chandraseta** [comment]
Closed due to inactivity

**Comment by arun-sagar** [comment]
How can we modify the algorithm so that it detects faces in any angle?

**Comment by chandraseta** [comment]
The function for finding faces are located in `src/face_detection.py`, on line 18:
`faces = faceCascade.detectMultiScale(...)`

It is a built-in function from OpenCV, but it is possible to create your own algorithm to replace that built-in function. However, I do not know specifically how to improve the current algorithm.
